import { Router } from 'express';
import { searchTechnicians, getTechnician, getTechnicianReviews, getTechnicianAvailability, updateMyProfile, getMyProfile } from '../controllers/tecnico.controller';
import { authMiddleware } from '../middlewares/auth.middleware';
const router = Router();
router.get('/',                    searchTechnicians);
router.get('/me',                  authMiddleware, getMyProfile);
router.get('/:id',                 getTechnician);
router.get('/:id/reviews',         getTechnicianReviews);
router.get('/:id/availability',    getTechnicianAvailability);
router.put('/me',                  authMiddleware, updateMyProfile);
export default router;
